#ifndef PHP_HTML5_DOM_INTERFACES_H
#define PHP_HTML5_DOM_INTERFACES_H

/* DO NOT EDIT! */
/* This file was autogenerated by the utils/mk_interfaces.php script. */

#include "php.h"

<?php foreach ($classes as $ce): ?>
zend_class_entry *<?= $ce['id'] ?>_ce;
<?php endforeach; ?>

void html5_dom_interfaces_init();
void html5_dom_interfaces_unload();

/*
 * Constants
 * */

<?php foreach ($classes as $ce): ?><?php if ($ce['const']): ?>
/* <?= $ce['name'] ?> */
<?php foreach ($ce['const'] as $const): ?>
#define <?= $ce['prefix']."__".$const['name'] ?> <?= $const['value'] ?>

<?php endforeach; ?>
	
<?php endif; ?><?php endforeach; ?>

/*
 * Methods
 * */

<?php foreach ($classes as $ce): ?><?php if ($ce['methods']): ?>
/* <?= $ce['name'] ?> */
<?php foreach ($ce['methods'] as $method): ?>
PHP_METHOD(<?= $ce['prefix'] ?>, <?= $method['name'] ?>);
<?php endforeach; ?>

<?php endif; ?><?php endforeach; ?>

/*
 * Properties
 * */

<?php foreach ($classes as $ce): ?><?php if ($ce['props']): ?>
/* <?= $ce['name'] ?> */
<?php foreach ($ce['props'] as $var): ?>
int <?= $ce['id'] ?>__<?= $var ?>(html5_dom_object_wrap *obj, zval *val, int write, int debug);
<?php endforeach; ?>

<?php endif; ?><?php endforeach; ?>

#endif // PHP_HTML5_DOM_INTERFACES_H
