/* DO NOT EDIT! */
/* This file was autogenerated by the utils/mk_interfaces.php script. */

#include <php7/utils.h>
#include <php7/interfaces.h>

#include "zend_exceptions.h"
#include "zend_smart_str.h"

/*
 * Property handlers
 * */
 
static zend_object_handlers object_handlers;

<?php foreach ($classes as $ce): ?><?php if ($ce['props']): ?>
static HashTable <?= $ce['id'] ?>_prop_handlers;
<?php endif; ?><?php endforeach; ?>

/*
 * Arguments info
 * */

<?php
foreach ($classes as $ce) {
	if (!$ce['methods'])
		continue;
	
	echo "/* ".$ce['name']." */\n";
	
	foreach ($ce['methods'] as $method) {
		switch ($method['hint']['type']) {
			case "obj_info":
				printf("ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_%s, %d, %d, %s, %d)\n", 
					$ce['prefix']."_".$method['name'], (int) $method['hint']['ref'], $method['required'], 
					addslashes($method['hint']['value']), (int) $method['hint']['null']);
			break;
			
			case "type_info":
				printf("ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_%s, %d, %d, %s, %d)\n", 
					$ce['prefix']."_".$method['name'], (int) $method['hint']['ref'], $method['required'], 
					addslashes($method['hint']['value']), (int) $method['hint']['null']);
			break;
			
			default:
				printf("ZEND_BEGIN_ARG_INFO_EX(arginfo_class_%s, 0, %d, %d)\n", 
					$ce['prefix']."_".$method['name'], (int) $method['hint']['ref'], $method['required']);
			break;
		}
		
		foreach ($method['arginfo'] as $arginfo) {
			$macro = $arginfo['hint']['variadic'] ? 'ARG_VARIADIC' : 'ARG';
			
			switch ($arginfo['hint']['type']) {
				case "obj_info":
					printf("\tZEND_%s_OBJ_INFO(%d, %s, %s, %d)\n", 
						$macro, (int) $arginfo['hint']['ref'], $arginfo['name'], 
						addslashes($arginfo['hint']['value']), (int) $arginfo['hint']['null']);
				break;
				
				case "type_info":
					printf("\tZEND_%s_TYPE_INFO(%d, %s, %s, %d)\n", 
						$macro, (int) $arginfo['hint']['ref'], $arginfo['name'], 
						addslashes($arginfo['hint']['value']), (int) $arginfo['hint']['null']);
				break;
				
				default:
					printf("\tZEND_%s_INFO(%d, %s)\n", $macro, 0, $arginfo['name']);
				break;
			}
		}
		
		echo "ZEND_END_ARG_INFO();\n\n";
	}
}
?>

/*
 * Methods info
 * */
 
<?php foreach ($classes as $ce): ?>
/* <?= $ce['name'] ?> */
static zend_function_entry <?= $ce['id'] ?>_methods[] = {
<?php foreach ($ce['methods'] as $method): ?>
	PHP_ME(<?= $ce['prefix'] ?>, <?= $method['name'] ?>, arginfo_class_<?= $ce['prefix'] ?>_<?= $method['name'] ?>, <?= $method['modifiers'] ?>)
<?php endforeach; ?>
	PHP_FE_END
};

<?php endforeach; ?>

/*
 * Functions
 * */
static zend_object *_create_object(zend_class_entry *ce TSRMLS_DC) {
	html5_dom_object_wrap *intern = html5_dom_object_wrap_create(ce, &object_handlers);
	
<?php $i = 0; ?>
<?php foreach ($classes as $ce): ?><?php if ($ce['props']): ?>
	/* <?= $ce['name'] ?> */
	<?= $i++ ? 'else if' : 'if' ?> (ce == <?= $ce['id'] ?>_ce) {
		intern->prop_handler = &<?= $ce['id'] ?>_prop_handlers;
	}
<?php endif; ?><?php endforeach; ?>
	/* Without properties */
	else {
		intern->prop_handler = NULL;
	}
	
	DOM_GC_TRACE("[NEW] %s (refs=%d)", ce->name->val, GC_REFCOUNT(&intern->std));
	
	return &intern->std;
}

static void _free_object(zend_object *object TSRMLS_DC) {
	html5_dom_object_wrap *intern = html5_dom_object_unwrap(object);
	
	DOM_GC_TRACE("[DESTROY] %s (refs=%d)", object->ce->name->val, GC_REFCOUNT(&intern->std));
	
	html5_dom_object_wrap_free(intern);
}

void html5_dom_interfaces_init() {
	memcpy(&object_handlers, zend_get_std_object_handlers(), sizeof(zend_object_handlers));
	object_handlers.offset					= XtOffsetOf(html5_dom_object_wrap, std);
	object_handlers.free_obj				= _free_object;
	object_handlers.clone_obj				= NULL;
	
	object_handlers.read_property			= html5_dom_read_property;
	object_handlers.write_property			= html5_dom_write_property;
	object_handlers.get_property_ptr_ptr	= html5_dom_get_property_ptr_ptr;
	object_handlers.has_property			= html5_dom_has_property;
	object_handlers.get_debug_info			= html5_dom_get_debug_info;
	
	zend_class_entry ce;
<?php foreach ($classes as $ce): ?>
	/* <?= $ce['name'] ?> */
<?php if ($ce['props']): ?>
	html5_dom_prop_handler_list <?= $ce['id'] ?>_handlers[] = {
<?php foreach ($ce['props'] as $var): ?>
		{"<?= $var ?>", <?= $ce['id']."__".$var ?>}, 
<?php endforeach; ?>
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&<?= $ce['id'] ?>_prop_handlers, <?= $ce['id'] ?>_handlers);
<?php else: ?>
	// no prop handlers
<?php endif; ?>
	
	INIT_CLASS_ENTRY(ce, "<?= addslashes($ce['name']) ?>", <?= $ce['id'] ?>_methods);
	ce.create_object = _create_object;
	<?= $ce['id'] ?>_ce = zend_register_internal_class(&ce);
	
<?php endforeach; ?>
}

void html5_dom_interfaces_unload() {
<?php foreach ($classes as $ce): ?><?php if ($ce['props']): ?>
	zend_hash_destroy(&<?= $ce['id'] ?>_prop_handlers);
<?php endif; ?><?php endforeach; ?>
}
