#ifndef PHP_HTML5_DOM_INTERFACES_H
#define PHP_HTML5_DOM_INTERFACES_H

/* DO NOT EDIT! */
/* This file was autogenerated by the utils/mk_interfaces.php script. */

#include "php.h"
#include "utils.h"

<?php foreach ($classes as $ce): ?>
zend_class_entry *<?= $ce['ref'] ?>;
<?php endforeach; ?>

void html5_dom_interfaces_init();
void html5_dom_interfaces_unload();

/*
 * Constants
 * */

<?php foreach ($classes as $ce): ?><?php if ($ce['consts']): ?>
/* <?= $ce['name'] ?> */
<?php foreach ($ce['consts'] as $const): ?>
#define <?= $ce['prefix']."__".$const['name'] ?> <?= $const['value'] ?>

<?php endforeach; ?>
	
<?php endif; ?><?php endforeach; ?>

/*
 * Methods
 * */

<?php foreach ($all_classes as $ce): ?><?php if ($ce['own_methods']): ?>
/* <?= $ce['name'] ?> */
<?php foreach ($ce['own_methods'] as $method): ?>
PHP_METHOD(<?= $ce['prefix'] ?>, <?= $method['name'] ?>);
<?php endforeach; ?>

<?php endif; ?><?php endforeach; ?>

/*
 * Properties
 * */

<?php foreach ($all_classes as $ce): ?><?php if ($ce['own_props']): ?>
/* <?= $ce['name'] ?> */
<?php foreach ($ce['own_props'] as $prop): ?>
int <?= $prop['prefix'] ?>__<?= $prop['name'] ?>(html5_dom_object_wrap *obj, zval *val, int write, int debug);
<?php endforeach; ?>

<?php endif; ?><?php endforeach; ?>

#endif // PHP_HTML5_DOM_INTERFACES_H
