#ifndef PHP_HTML5_DOM_INTERFACES_H
#define PHP_HTML5_DOM_INTERFACES_H

/* DO NOT EDIT! */
/* This file was autogenerated by the utils/mk_interfaces.php script. */

#include "port.h"
#include "object_wrap.h"

#define DOM_GC_TRACE(msg, ...) fprintf(stderr, "[GC] " msg "\n", ##__VA_ARGS__);
// #define DOM_GC_TRACE(...)

zend_class_entry *html5_dom_ce;
zend_class_entry *html5_dom_parser_ce;
zend_class_entry *html5_dom_streamparser_ce;
zend_class_entry *html5_dom_domexception_ce;
zend_class_entry *html5_dom_eventtarget_ce;
zend_class_entry *html5_dom_node_ce;
zend_class_entry *html5_dom_document_ce;
zend_class_entry *html5_dom_documentfragment_ce;
zend_class_entry *html5_dom_documenttype_ce;
zend_class_entry *html5_dom_attr_ce;
zend_class_entry *html5_dom_characterdata_ce;
zend_class_entry *html5_dom_text_ce;
zend_class_entry *html5_dom_cdatasection_ce;
zend_class_entry *html5_dom_comment_ce;
zend_class_entry *html5_dom_processinginstruction_ce;
zend_class_entry *html5_dom_element_ce;
zend_class_entry *html5_dom_htmlcollection_ce;
zend_class_entry *html5_dom_nodelist_ce;
zend_class_entry *html5_dom_domtokenlist_ce;
zend_class_entry *html5_dom_namednodemap_ce;

void html5_dom_interfaces_init();
void html5_dom_interfaces_unload();

/*
 * Constants
 * */

/* HTML5\DOM\Node */
#define HTML5_DOM_Node__DOCUMENT_POSITION_DISCONNECTED 1
#define HTML5_DOM_Node__DOCUMENT_POSITION_PRECEDING 2
#define HTML5_DOM_Node__DOCUMENT_POSITION_FOLLOWING 4
#define HTML5_DOM_Node__DOCUMENT_POSITION_CONTAINS 8
#define HTML5_DOM_Node__DOCUMENT_POSITION_CONTAINED_BY 16
#define HTML5_DOM_Node__DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC 32
	

/*
 * Methods
 * */

/* HTML5\DOM */
PHP_METHOD(HTML5_DOM, parse);

/* HTML5\DOM\Parser */
PHP_METHOD(HTML5_DOM_Parser, __construct);
PHP_METHOD(HTML5_DOM_Parser, parse);

/* HTML5\DOM\StreamParser */
PHP_METHOD(HTML5_DOM_StreamParser, __construct);
PHP_METHOD(HTML5_DOM_StreamParser, begin);
PHP_METHOD(HTML5_DOM_StreamParser, parse);
PHP_METHOD(HTML5_DOM_StreamParser, end);

/* HTML5\DOM\EventTarget */
PHP_METHOD(HTML5_DOM_EventTarget, __construct);

/* HTML5\DOM\Node */
PHP_METHOD(HTML5_DOM_Node, getRootNode);
PHP_METHOD(HTML5_DOM_Node, hasChildNodes);
PHP_METHOD(HTML5_DOM_Node, normalize);
PHP_METHOD(HTML5_DOM_Node, cloneNode);
PHP_METHOD(HTML5_DOM_Node, isEqualNode);
PHP_METHOD(HTML5_DOM_Node, isSameNode);
PHP_METHOD(HTML5_DOM_Node, compareDocumentPosition);
PHP_METHOD(HTML5_DOM_Node, contains);
PHP_METHOD(HTML5_DOM_Node, insertBefore);
PHP_METHOD(HTML5_DOM_Node, appendChild);
PHP_METHOD(HTML5_DOM_Node, replaceChild);
PHP_METHOD(HTML5_DOM_Node, removeChild);

/* HTML5\DOM\Document */
PHP_METHOD(HTML5_DOM_Document, createElement);
PHP_METHOD(HTML5_DOM_Document, createElementNS);
PHP_METHOD(HTML5_DOM_Document, createDocumentFragment);
PHP_METHOD(HTML5_DOM_Document, createTextNode);
PHP_METHOD(HTML5_DOM_Document, createComment);
PHP_METHOD(HTML5_DOM_Document, createCDATASection);
PHP_METHOD(HTML5_DOM_Document, createProcessingInstruction);
PHP_METHOD(HTML5_DOM_Document, importNode);
PHP_METHOD(HTML5_DOM_Document, adoptNode);
PHP_METHOD(HTML5_DOM_Document, createAttribute);
PHP_METHOD(HTML5_DOM_Document, createAttributeNS);

/* HTML5\DOM\CharacterData */
PHP_METHOD(HTML5_DOM_CharacterData, substringData);
PHP_METHOD(HTML5_DOM_CharacterData, appendData);
PHP_METHOD(HTML5_DOM_CharacterData, insertData);
PHP_METHOD(HTML5_DOM_CharacterData, deleteData);
PHP_METHOD(HTML5_DOM_CharacterData, replaceData);

/* HTML5\DOM\Text */
PHP_METHOD(HTML5_DOM_Text, splitText);

/* HTML5\DOM\Element */
PHP_METHOD(HTML5_DOM_Element, hasAttributes);
PHP_METHOD(HTML5_DOM_Element, getAttributeNames);
PHP_METHOD(HTML5_DOM_Element, getAttribute);
PHP_METHOD(HTML5_DOM_Element, getAttributeNS);
PHP_METHOD(HTML5_DOM_Element, setAttribute);
PHP_METHOD(HTML5_DOM_Element, setAttributeNS);
PHP_METHOD(HTML5_DOM_Element, removeAttribute);
PHP_METHOD(HTML5_DOM_Element, removeAttributeNS);
PHP_METHOD(HTML5_DOM_Element, toggleAttribute);
PHP_METHOD(HTML5_DOM_Element, toggleAttributeNS);
PHP_METHOD(HTML5_DOM_Element, hasAttribute);
PHP_METHOD(HTML5_DOM_Element, hasAttributeNS);
PHP_METHOD(HTML5_DOM_Element, getAttributeNode);
PHP_METHOD(HTML5_DOM_Element, getAttributeNodeNS);
PHP_METHOD(HTML5_DOM_Element, setAttributeNode);
PHP_METHOD(HTML5_DOM_Element, setAttributeNodeNS);
PHP_METHOD(HTML5_DOM_Element, removeAttributeNode);
PHP_METHOD(HTML5_DOM_Element, closest);
PHP_METHOD(HTML5_DOM_Element, matches);
PHP_METHOD(HTML5_DOM_Element, insertAdjacentElement);
PHP_METHOD(HTML5_DOM_Element, insertAdjacentText);
PHP_METHOD(HTML5_DOM_Element, insertAdjacentHTML);

/* HTML5\DOM\HTMLCollection */
PHP_METHOD(HTML5_DOM_HTMLCollection, item);
PHP_METHOD(HTML5_DOM_HTMLCollection, namedItem);
PHP_METHOD(HTML5_DOM_HTMLCollection, current);
PHP_METHOD(HTML5_DOM_HTMLCollection, key);
PHP_METHOD(HTML5_DOM_HTMLCollection, next);
PHP_METHOD(HTML5_DOM_HTMLCollection, rewind);
PHP_METHOD(HTML5_DOM_HTMLCollection, valid);
PHP_METHOD(HTML5_DOM_HTMLCollection, offsetExists);
PHP_METHOD(HTML5_DOM_HTMLCollection, offsetGet);
PHP_METHOD(HTML5_DOM_HTMLCollection, offsetSet);
PHP_METHOD(HTML5_DOM_HTMLCollection, offsetUnset);
PHP_METHOD(HTML5_DOM_HTMLCollection, count);

/* HTML5\DOM\NodeList */
PHP_METHOD(HTML5_DOM_NodeList, item);
PHP_METHOD(HTML5_DOM_NodeList, current);
PHP_METHOD(HTML5_DOM_NodeList, key);
PHP_METHOD(HTML5_DOM_NodeList, next);
PHP_METHOD(HTML5_DOM_NodeList, rewind);
PHP_METHOD(HTML5_DOM_NodeList, valid);
PHP_METHOD(HTML5_DOM_NodeList, offsetExists);
PHP_METHOD(HTML5_DOM_NodeList, offsetGet);
PHP_METHOD(HTML5_DOM_NodeList, offsetSet);
PHP_METHOD(HTML5_DOM_NodeList, offsetUnset);
PHP_METHOD(HTML5_DOM_NodeList, count);

/* HTML5\DOM\DOMTokenList */
PHP_METHOD(HTML5_DOM_DOMTokenList, item);
PHP_METHOD(HTML5_DOM_DOMTokenList, contains);
PHP_METHOD(HTML5_DOM_DOMTokenList, add);
PHP_METHOD(HTML5_DOM_DOMTokenList, remove);
PHP_METHOD(HTML5_DOM_DOMTokenList, toggle);
PHP_METHOD(HTML5_DOM_DOMTokenList, replace);
PHP_METHOD(HTML5_DOM_DOMTokenList, supports);
PHP_METHOD(HTML5_DOM_DOMTokenList, current);
PHP_METHOD(HTML5_DOM_DOMTokenList, key);
PHP_METHOD(HTML5_DOM_DOMTokenList, next);
PHP_METHOD(HTML5_DOM_DOMTokenList, rewind);
PHP_METHOD(HTML5_DOM_DOMTokenList, valid);
PHP_METHOD(HTML5_DOM_DOMTokenList, offsetExists);
PHP_METHOD(HTML5_DOM_DOMTokenList, offsetGet);
PHP_METHOD(HTML5_DOM_DOMTokenList, offsetSet);
PHP_METHOD(HTML5_DOM_DOMTokenList, offsetUnset);
PHP_METHOD(HTML5_DOM_DOMTokenList, count);

/* HTML5\DOM\NamedNodeMap */
PHP_METHOD(HTML5_DOM_NamedNodeMap, item);
PHP_METHOD(HTML5_DOM_NamedNodeMap, getNamedItem);
PHP_METHOD(HTML5_DOM_NamedNodeMap, getNamedItemNS);
PHP_METHOD(HTML5_DOM_NamedNodeMap, setNamedItem);
PHP_METHOD(HTML5_DOM_NamedNodeMap, setNamedItemNS);
PHP_METHOD(HTML5_DOM_NamedNodeMap, removeNamedItem);
PHP_METHOD(HTML5_DOM_NamedNodeMap, removeNamedItemNS);
PHP_METHOD(HTML5_DOM_NamedNodeMap, current);
PHP_METHOD(HTML5_DOM_NamedNodeMap, key);
PHP_METHOD(HTML5_DOM_NamedNodeMap, next);
PHP_METHOD(HTML5_DOM_NamedNodeMap, rewind);
PHP_METHOD(HTML5_DOM_NamedNodeMap, valid);
PHP_METHOD(HTML5_DOM_NamedNodeMap, offsetExists);
PHP_METHOD(HTML5_DOM_NamedNodeMap, offsetGet);
PHP_METHOD(HTML5_DOM_NamedNodeMap, offsetSet);
PHP_METHOD(HTML5_DOM_NamedNodeMap, offsetUnset);
PHP_METHOD(HTML5_DOM_NamedNodeMap, count);

/* HTML5\DOM\NonElementParentNode */
PHP_METHOD(HTML5_DOM_NonElementParentNode, getElementById);

/* HTML5\DOM\ParentNode */
PHP_METHOD(HTML5_DOM_ParentNode, getElementsByTagName);
PHP_METHOD(HTML5_DOM_ParentNode, getElementsByTagNameNS);
PHP_METHOD(HTML5_DOM_ParentNode, getElementsByClassName);
PHP_METHOD(HTML5_DOM_ParentNode, prepend);
PHP_METHOD(HTML5_DOM_ParentNode, append);
PHP_METHOD(HTML5_DOM_ParentNode, querySelector);
PHP_METHOD(HTML5_DOM_ParentNode, querySelectorAll);

/* HTML5\DOM\ChildNode */
PHP_METHOD(HTML5_DOM_ChildNode, before);
PHP_METHOD(HTML5_DOM_ChildNode, after);
PHP_METHOD(HTML5_DOM_ChildNode, replaceWith);
PHP_METHOD(HTML5_DOM_ChildNode, remove);

/* HTML5\DOM\DocumentNonStandart */
PHP_METHOD(HTML5_DOM_DocumentNonStandart, getParseErrors);


/*
 * Properties
 * */

/* HTML5\DOM\DOMException */
int html5_dom_domexception__name(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\Node */
int html5_dom_node__nodeType(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__nodeName(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__baseURI(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__isConnected(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__ownerDocument(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__parentNode(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__parentElement(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__childNodes(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__firstChild(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__lastChild(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__previousSibling(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__nextSibling(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__nodeValue(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__textContent(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__private(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_node__private_set(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\Document */
int html5_dom_document__URL(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__documentURI(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__origin(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__compatMode(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__characterSet(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__charset(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__inputEncoding(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__contentType(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__doctype(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_document__documentElement(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\DocumentType */
int html5_dom_documenttype__name(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_documenttype__publicId(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_documenttype__systemId(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\Attr */
int html5_dom_attr__namespaceURI(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_attr__prefix(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_attr__localName(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_attr__name(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_attr__value(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_attr__value_set(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_attr__ownerElement(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\CharacterData */
int html5_dom_characterdata__data(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_characterdata__data_set(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_characterdata__length(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\Text */
int html5_dom_text__wholeText(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\ProcessingInstruction */
int html5_dom_processinginstruction__target(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\Element */
int html5_dom_element__namespaceURI(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__prefix(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__localName(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__tagName(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__id(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__id_set(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__className(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__className_set(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__classList(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__attributes(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__innerHTML(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__innerHTML_set(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__outerHTML(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_element__outerHTML_set(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\HTMLCollection */
int html5_dom_htmlcollection__length(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\NodeList */
int html5_dom_nodelist__length(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\DOMTokenList */
int html5_dom_domtokenlist__length(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_domtokenlist__value(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_domtokenlist__value_set(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\NamedNodeMap */
int html5_dom_namednodemap__length(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\ParentNode */
int html5_dom_parentnode__children(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_parentnode__firstElementChild(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_parentnode__lastElementChild(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_parentnode__childElementCount(html5_dom_object_wrap_t *obj, zval *val);

/* HTML5\DOM\NonDocumentTypeChildNode */
int html5_dom_nondocumenttypechildnode__previousElementSibling(html5_dom_object_wrap_t *obj, zval *val);
int html5_dom_nondocumenttypechildnode__nextElementSibling(html5_dom_object_wrap_t *obj, zval *val);


#endif // PHP_HTML5_DOM_INTERFACES_H
