/* DO NOT EDIT! */
/* This file was autogenerated by the utils/mk_interfaces.php script. */

#include "interfaces.h"
#include "zend_exceptions.h"
#include "zend_interfaces.h"

#include "lexbor/dom/interfaces/node.h"
#include "lexbor/dom/exception.h"

/*
 * Property handlers
 * */
 
static zend_object_handlers object_handlers;

static HashTable html5_dom_domexception_prop_handlers;
static HashTable html5_dom_node_prop_handlers;
static HashTable html5_dom_document_prop_handlers;
static HashTable html5_dom_documentfragment_prop_handlers;
static HashTable html5_dom_documenttype_prop_handlers;
static HashTable html5_dom_attr_prop_handlers;
static HashTable html5_dom_characterdata_prop_handlers;
static HashTable html5_dom_text_prop_handlers;
static HashTable html5_dom_cdatasection_prop_handlers;
static HashTable html5_dom_comment_prop_handlers;
static HashTable html5_dom_processinginstruction_prop_handlers;
static HashTable html5_dom_element_prop_handlers;
static HashTable html5_dom_htmlcollection_prop_handlers;
static HashTable html5_dom_nodelist_prop_handlers;
static HashTable html5_dom_domtokenlist_prop_handlers;
static HashTable html5_dom_namednodemap_prop_handlers;

/*
 * Arguments info
 * */

/* HTML5\DOM */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_parse, 0, 1, HTML5\\DOM\\Document, 0)
	ZEND_ARG_TYPE_INFO(0, html, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\Parser */
ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_Parser___construct, 0, 0, 0)
	ZEND_ARG_INFO(0, options)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Parser_parse, 0, 1, HTML5\\DOM\\DOM\\Document, 0)
	ZEND_ARG_TYPE_INFO(0, html, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\StreamParser */
ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_StreamParser___construct, 0, 0, 0)
	ZEND_ARG_INFO(0, options)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_StreamParser_begin, 0, 0, HTML5\\DOM\\DOM\\Document, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_StreamParser_parse, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, html, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_StreamParser_end, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\EventTarget */
ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_EventTarget___construct, 0, 0, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\Node */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Node_getRootNode, 0, 0, HTML5\\DOM\\Node, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Node_hasChildNodes, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Node_normalize, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Node_cloneNode, 0, 0, HTML5\\DOM\\Node, 0)
	ZEND_ARG_TYPE_INFO(0, deep, _IS_BOOL, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Node_isEqualNode, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, otherNode, HTML5\\DOM\\Node, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Node_isSameNode, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, otherNode, HTML5\\DOM\\Node, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Node_compareDocumentPosition, 0, 1, IS_LONG, 0)
	ZEND_ARG_OBJ_INFO(0, other, HTML5\\DOM\\Node, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Node_contains, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_OBJ_INFO(0, other, HTML5\\DOM\\Node, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Node_insertBefore, 0, 2, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, node, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, child, HTML5\\DOM\\Node, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Node_appendChild, 0, 1, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, child, HTML5\\DOM\\Node, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Node_replaceChild, 0, 2, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, node, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, child, HTML5\\DOM\\Node, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Node_removeChild, 0, 1, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, child, HTML5\\DOM\\Node, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\Document */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createElement, 0, 1, HTML5\\DOM\\Element, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createElementNS, 0, 2, HTML5\\DOM\\Element, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createDocumentFragment, 0, 0, HTML5\\DOM\\DocumentFragment, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createTextNode, 0, 1, HTML5\\DOM\\Text, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createComment, 0, 1, HTML5\\DOM\\Comment, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createCDATASection, 0, 1, HTML5\\DOM\\CDATASection, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createProcessingInstruction, 0, 2, HTML5\\DOM\\ProcessingInstruction, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_importNode, 0, 1, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, node, HTML5\\DOM\\Node, 0)
	ZEND_ARG_TYPE_INFO(0, deep, _IS_BOOL, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_adoptNode, 0, 1, HTML5\\DOM\\Node, 0)
	ZEND_ARG_OBJ_INFO(0, data, HTML5\\DOM\\Node, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createAttribute, 0, 1, HTML5\\DOM\\Attr, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Document_createAttributeNS, 0, 2, HTML5\\DOM\\Attr, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\CharacterData */
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_CharacterData_substringData, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_CharacterData_appendData, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_CharacterData_insertData, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_CharacterData_deleteData, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_CharacterData_replaceData, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, count, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\Text */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Text_splitText, 0, 1, HTML5\\DOM\\Text, 0)
	ZEND_ARG_TYPE_INFO(0, offset, IS_LONG, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\Element */
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_hasAttributes, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_getAttributeNames, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_getAttribute, 0, 1, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_getAttributeNS, 0, 2, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_setAttribute, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_setAttributeNS, 0, 3, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_removeAttribute, 0, 1, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_removeAttributeNS, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_toggleAttribute, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, force, _IS_BOOL, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_toggleAttributeNS, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, force, _IS_BOOL, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_hasAttribute, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_hasAttributeNS, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_getAttributeNode, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_getAttributeNodeNS, 0, 2, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_setAttributeNode, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_OBJ_INFO(0, attr, HTML5\\DOM\\Attr, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_setAttributeNodeNS, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_OBJ_INFO(0, attr, HTML5\\DOM\\Attr, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_removeAttributeNode, 0, 1, HTML5\\DOM\\Attr, 0)
	ZEND_ARG_OBJ_INFO(0, attr, HTML5\\DOM\\Attr, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_closest, 0, 1, HTML5\\DOM\\Node, 1)
	ZEND_ARG_INFO(0, selectors)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_matches, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, selectors)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_Element_insertAdjacentElement, 0, 2, HTML5\\DOM\\Node, 1)
	ZEND_ARG_TYPE_INFO(0, where, IS_STRING, 0)
	ZEND_ARG_OBJ_INFO(0, element, HTML5\\DOM\\Node, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_insertAdjacentText, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, where, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_Element_insertAdjacentHTML, 0, 2, IS_VOID, 0)
	ZEND_ARG_TYPE_INFO(0, where, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, html, IS_STRING, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\HTMLCollection */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_item, 0, 1, HTML5\\DOM\\Node, 1)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_namedItem, 0, 1, HTML5\\DOM\\Node, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_current, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_key, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_next, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_rewind, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_valid, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_offsetExists, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_offsetGet, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_offsetSet, 0, 0, 2)
	ZEND_ARG_INFO(0, offset)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_offsetUnset, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_HTMLCollection_count, 0, 0, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\NodeList */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NodeList_item, 0, 1, HTML5\\DOM\\Node, 1)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_current, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_key, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_next, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_rewind, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_valid, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_offsetExists, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_offsetGet, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_offsetSet, 0, 0, 2)
	ZEND_ARG_INFO(0, offset)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_offsetUnset, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NodeList_count, 0, 0, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\DOMTokenList */
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_item, 0, 1, IS_STRING, 1)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_contains, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, token, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_add, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_TYPE_INFO(0, tokens, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_remove, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_TYPE_INFO(0, tokens, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_toggle, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, token, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, force, _IS_BOOL, 1)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_replace, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, token, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, newToken, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_supports, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, token, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_current, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_key, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_next, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_rewind, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_valid, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_offsetExists, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_offsetGet, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_offsetSet, 0, 0, 2)
	ZEND_ARG_INFO(0, offset)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_offsetUnset, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_DOMTokenList_count, 0, 0, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\NamedNodeMap */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_item, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_getNamedItem, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_getNamedItemNS, 0, 2, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_setNamedItem, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_OBJ_INFO(0, attr, HTML5\\DOM\\Attr, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_setNamedItemNS, 0, 1, HTML5\\DOM\\Attr, 1)
	ZEND_ARG_OBJ_INFO(0, attr, HTML5\\DOM\\Attr, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_removeNamedItem, 0, 1, HTML5\\DOM\\Attr, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_removeNamedItemNS, 0, 2, HTML5\\DOM\\Attr, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_current, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_key, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_next, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_rewind, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_valid, 0, 0, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_offsetExists, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_offsetGet, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_offsetSet, 0, 0, 2)
	ZEND_ARG_INFO(0, offset)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_offsetUnset, 0, 0, 1)
	ZEND_ARG_INFO(0, offset)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NamedNodeMap_count, 0, 0, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\NonElementParentNode */
ZEND_BEGIN_ARG_INFO_EX(arginfo_class_HTML5_DOM_NonElementParentNode_getElementById, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, elementId, IS_STRING, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\ParentNode */
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_getElementsByTagName, 0, 1, HTML5\\DOM\\HTMLCollection, 0)
	ZEND_ARG_TYPE_INFO(0, qualifiedName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_getElementsByTagNameNS, 0, 2, HTML5\\DOM\\HTMLCollection, 0)
	ZEND_ARG_TYPE_INFO(0, namespace, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, localName, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_getElementsByClassName, 0, 1, HTML5\\DOM\\HTMLCollection, 0)
	ZEND_ARG_TYPE_INFO(0, classNames, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_prepend, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_INFO(0, nodes)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_append, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_INFO(0, nodes)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_querySelector, 0, 1, HTML5\\DOM\\Node, 1)
	ZEND_ARG_TYPE_INFO(0, selectors, IS_STRING, 0)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_HTML5_DOM_ParentNode_querySelectorAll, 0, 1, HTML5\\DOM\\NodeList, 0)
	ZEND_ARG_TYPE_INFO(0, selectors, IS_STRING, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\ChildNode */
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_ChildNode_before, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_INFO(0, nodes)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_ChildNode_after, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_INFO(0, nodes)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_ChildNode_replaceWith, 0, 0, IS_VOID, 0)
	ZEND_ARG_VARIADIC_INFO(0, nodes)
ZEND_END_ARG_INFO();

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_ChildNode_remove, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO();

/* HTML5\DOM\DocumentNonStandart */
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_HTML5_DOM_DocumentNonStandart_getParseErrors, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO();


/*
 * Methods info
 * */
 
/* HTML5\DOM */
static zend_function_entry html5_dom_methods[] = {
	PHP_ME(HTML5_DOM, parse, arginfo_class_HTML5_DOM_parse, ZEND_ACC_STATIC | ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\Parser */
static zend_function_entry html5_dom_parser_methods[] = {
	PHP_ME(HTML5_DOM_Parser, __construct, arginfo_class_HTML5_DOM_Parser___construct, ZEND_ACC_PRIVATE | ZEND_ACC_CTOR)
	PHP_ME(HTML5_DOM_Parser, parse, arginfo_class_HTML5_DOM_Parser_parse, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\StreamParser */
static zend_function_entry html5_dom_streamparser_methods[] = {
	PHP_ME(HTML5_DOM_StreamParser, __construct, arginfo_class_HTML5_DOM_StreamParser___construct, ZEND_ACC_PRIVATE | ZEND_ACC_CTOR)
	PHP_ME(HTML5_DOM_StreamParser, begin, arginfo_class_HTML5_DOM_StreamParser_begin, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_StreamParser, parse, arginfo_class_HTML5_DOM_StreamParser_parse, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_StreamParser, end, arginfo_class_HTML5_DOM_StreamParser_end, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\DOMException */
static zend_function_entry html5_dom_domexception_methods[] = {
	PHP_FE_END
};

/* HTML5\DOM\EventTarget */
static zend_function_entry html5_dom_eventtarget_methods[] = {
	PHP_ME(HTML5_DOM_EventTarget, __construct, arginfo_class_HTML5_DOM_EventTarget___construct, ZEND_ACC_PRIVATE | ZEND_ACC_CTOR)
	PHP_FE_END
};

/* HTML5\DOM\Node */
static zend_function_entry html5_dom_node_methods[] = {
	PHP_ME(HTML5_DOM_Node, getRootNode, arginfo_class_HTML5_DOM_Node_getRootNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, hasChildNodes, arginfo_class_HTML5_DOM_Node_hasChildNodes, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, normalize, arginfo_class_HTML5_DOM_Node_normalize, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, cloneNode, arginfo_class_HTML5_DOM_Node_cloneNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, isEqualNode, arginfo_class_HTML5_DOM_Node_isEqualNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, isSameNode, arginfo_class_HTML5_DOM_Node_isSameNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, compareDocumentPosition, arginfo_class_HTML5_DOM_Node_compareDocumentPosition, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, contains, arginfo_class_HTML5_DOM_Node_contains, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, insertBefore, arginfo_class_HTML5_DOM_Node_insertBefore, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, appendChild, arginfo_class_HTML5_DOM_Node_appendChild, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, replaceChild, arginfo_class_HTML5_DOM_Node_replaceChild, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Node, removeChild, arginfo_class_HTML5_DOM_Node_removeChild, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\Document */
static zend_function_entry html5_dom_document_methods[] = {
	PHP_ME(HTML5_DOM_Document, createElement, arginfo_class_HTML5_DOM_Document_createElement, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createElementNS, arginfo_class_HTML5_DOM_Document_createElementNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createDocumentFragment, arginfo_class_HTML5_DOM_Document_createDocumentFragment, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createTextNode, arginfo_class_HTML5_DOM_Document_createTextNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createComment, arginfo_class_HTML5_DOM_Document_createComment, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createCDATASection, arginfo_class_HTML5_DOM_Document_createCDATASection, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createProcessingInstruction, arginfo_class_HTML5_DOM_Document_createProcessingInstruction, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, importNode, arginfo_class_HTML5_DOM_Document_importNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, adoptNode, arginfo_class_HTML5_DOM_Document_adoptNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createAttribute, arginfo_class_HTML5_DOM_Document_createAttribute, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Document, createAttributeNS, arginfo_class_HTML5_DOM_Document_createAttributeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByTagName, arginfo_class_HTML5_DOM_ParentNode_getElementsByTagName, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByTagNameNS, arginfo_class_HTML5_DOM_ParentNode_getElementsByTagNameNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByClassName, arginfo_class_HTML5_DOM_ParentNode_getElementsByClassName, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, prepend, arginfo_class_HTML5_DOM_ParentNode_prepend, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, append, arginfo_class_HTML5_DOM_ParentNode_append, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, querySelector, arginfo_class_HTML5_DOM_ParentNode_querySelector, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, querySelectorAll, arginfo_class_HTML5_DOM_ParentNode_querySelectorAll, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NonElementParentNode, getElementById, arginfo_class_HTML5_DOM_NonElementParentNode_getElementById, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DocumentNonStandart, getParseErrors, arginfo_class_HTML5_DOM_DocumentNonStandart_getParseErrors, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\DocumentFragment */
static zend_function_entry html5_dom_documentfragment_methods[] = {
	PHP_ME(HTML5_DOM_ParentNode, getElementsByTagName, arginfo_class_HTML5_DOM_ParentNode_getElementsByTagName, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByTagNameNS, arginfo_class_HTML5_DOM_ParentNode_getElementsByTagNameNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByClassName, arginfo_class_HTML5_DOM_ParentNode_getElementsByClassName, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, prepend, arginfo_class_HTML5_DOM_ParentNode_prepend, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, append, arginfo_class_HTML5_DOM_ParentNode_append, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, querySelector, arginfo_class_HTML5_DOM_ParentNode_querySelector, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, querySelectorAll, arginfo_class_HTML5_DOM_ParentNode_querySelectorAll, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NonElementParentNode, getElementById, arginfo_class_HTML5_DOM_NonElementParentNode_getElementById, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\DocumentType */
static zend_function_entry html5_dom_documenttype_methods[] = {
	PHP_ME(HTML5_DOM_ChildNode, before, arginfo_class_HTML5_DOM_ChildNode_before, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, after, arginfo_class_HTML5_DOM_ChildNode_after, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, replaceWith, arginfo_class_HTML5_DOM_ChildNode_replaceWith, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, remove, arginfo_class_HTML5_DOM_ChildNode_remove, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\Attr */
static zend_function_entry html5_dom_attr_methods[] = {
	PHP_FE_END
};

/* HTML5\DOM\CharacterData */
static zend_function_entry html5_dom_characterdata_methods[] = {
	PHP_ME(HTML5_DOM_CharacterData, substringData, arginfo_class_HTML5_DOM_CharacterData_substringData, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_CharacterData, appendData, arginfo_class_HTML5_DOM_CharacterData_appendData, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_CharacterData, insertData, arginfo_class_HTML5_DOM_CharacterData_insertData, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_CharacterData, deleteData, arginfo_class_HTML5_DOM_CharacterData_deleteData, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_CharacterData, replaceData, arginfo_class_HTML5_DOM_CharacterData_replaceData, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, before, arginfo_class_HTML5_DOM_ChildNode_before, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, after, arginfo_class_HTML5_DOM_ChildNode_after, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, replaceWith, arginfo_class_HTML5_DOM_ChildNode_replaceWith, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ChildNode, remove, arginfo_class_HTML5_DOM_ChildNode_remove, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\Text */
static zend_function_entry html5_dom_text_methods[] = {
	PHP_ME(HTML5_DOM_Text, splitText, arginfo_class_HTML5_DOM_Text_splitText, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\CDATASection */
static zend_function_entry html5_dom_cdatasection_methods[] = {
	PHP_FE_END
};

/* HTML5\DOM\Comment */
static zend_function_entry html5_dom_comment_methods[] = {
	PHP_FE_END
};

/* HTML5\DOM\ProcessingInstruction */
static zend_function_entry html5_dom_processinginstruction_methods[] = {
	PHP_FE_END
};

/* HTML5\DOM\Element */
static zend_function_entry html5_dom_element_methods[] = {
	PHP_ME(HTML5_DOM_Element, hasAttributes, arginfo_class_HTML5_DOM_Element_hasAttributes, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, getAttributeNames, arginfo_class_HTML5_DOM_Element_getAttributeNames, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, getAttribute, arginfo_class_HTML5_DOM_Element_getAttribute, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, getAttributeNS, arginfo_class_HTML5_DOM_Element_getAttributeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, setAttribute, arginfo_class_HTML5_DOM_Element_setAttribute, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, setAttributeNS, arginfo_class_HTML5_DOM_Element_setAttributeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, removeAttribute, arginfo_class_HTML5_DOM_Element_removeAttribute, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, removeAttributeNS, arginfo_class_HTML5_DOM_Element_removeAttributeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, toggleAttribute, arginfo_class_HTML5_DOM_Element_toggleAttribute, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, toggleAttributeNS, arginfo_class_HTML5_DOM_Element_toggleAttributeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, hasAttribute, arginfo_class_HTML5_DOM_Element_hasAttribute, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, hasAttributeNS, arginfo_class_HTML5_DOM_Element_hasAttributeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, getAttributeNode, arginfo_class_HTML5_DOM_Element_getAttributeNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, getAttributeNodeNS, arginfo_class_HTML5_DOM_Element_getAttributeNodeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, setAttributeNode, arginfo_class_HTML5_DOM_Element_setAttributeNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, setAttributeNodeNS, arginfo_class_HTML5_DOM_Element_setAttributeNodeNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, removeAttributeNode, arginfo_class_HTML5_DOM_Element_removeAttributeNode, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, closest, arginfo_class_HTML5_DOM_Element_closest, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, matches, arginfo_class_HTML5_DOM_Element_matches, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, insertAdjacentElement, arginfo_class_HTML5_DOM_Element_insertAdjacentElement, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, insertAdjacentText, arginfo_class_HTML5_DOM_Element_insertAdjacentText, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_Element, insertAdjacentHTML, arginfo_class_HTML5_DOM_Element_insertAdjacentHTML, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByTagName, arginfo_class_HTML5_DOM_ParentNode_getElementsByTagName, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByTagNameNS, arginfo_class_HTML5_DOM_ParentNode_getElementsByTagNameNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, getElementsByClassName, arginfo_class_HTML5_DOM_ParentNode_getElementsByClassName, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, prepend, arginfo_class_HTML5_DOM_ParentNode_prepend, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, append, arginfo_class_HTML5_DOM_ParentNode_append, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, querySelector, arginfo_class_HTML5_DOM_ParentNode_querySelector, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_ParentNode, querySelectorAll, arginfo_class_HTML5_DOM_ParentNode_querySelectorAll, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\HTMLCollection */
static zend_function_entry html5_dom_htmlcollection_methods[] = {
	PHP_ME(HTML5_DOM_HTMLCollection, item, arginfo_class_HTML5_DOM_HTMLCollection_item, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, namedItem, arginfo_class_HTML5_DOM_HTMLCollection_namedItem, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, current, arginfo_class_HTML5_DOM_HTMLCollection_current, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, key, arginfo_class_HTML5_DOM_HTMLCollection_key, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, next, arginfo_class_HTML5_DOM_HTMLCollection_next, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, rewind, arginfo_class_HTML5_DOM_HTMLCollection_rewind, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, valid, arginfo_class_HTML5_DOM_HTMLCollection_valid, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, offsetExists, arginfo_class_HTML5_DOM_HTMLCollection_offsetExists, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, offsetGet, arginfo_class_HTML5_DOM_HTMLCollection_offsetGet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, offsetSet, arginfo_class_HTML5_DOM_HTMLCollection_offsetSet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, offsetUnset, arginfo_class_HTML5_DOM_HTMLCollection_offsetUnset, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_HTMLCollection, count, arginfo_class_HTML5_DOM_HTMLCollection_count, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\NodeList */
static zend_function_entry html5_dom_nodelist_methods[] = {
	PHP_ME(HTML5_DOM_NodeList, item, arginfo_class_HTML5_DOM_NodeList_item, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, current, arginfo_class_HTML5_DOM_NodeList_current, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, key, arginfo_class_HTML5_DOM_NodeList_key, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, next, arginfo_class_HTML5_DOM_NodeList_next, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, rewind, arginfo_class_HTML5_DOM_NodeList_rewind, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, valid, arginfo_class_HTML5_DOM_NodeList_valid, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, offsetExists, arginfo_class_HTML5_DOM_NodeList_offsetExists, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, offsetGet, arginfo_class_HTML5_DOM_NodeList_offsetGet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, offsetSet, arginfo_class_HTML5_DOM_NodeList_offsetSet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, offsetUnset, arginfo_class_HTML5_DOM_NodeList_offsetUnset, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NodeList, count, arginfo_class_HTML5_DOM_NodeList_count, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\DOMTokenList */
static zend_function_entry html5_dom_domtokenlist_methods[] = {
	PHP_ME(HTML5_DOM_DOMTokenList, item, arginfo_class_HTML5_DOM_DOMTokenList_item, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, contains, arginfo_class_HTML5_DOM_DOMTokenList_contains, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, add, arginfo_class_HTML5_DOM_DOMTokenList_add, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, remove, arginfo_class_HTML5_DOM_DOMTokenList_remove, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, toggle, arginfo_class_HTML5_DOM_DOMTokenList_toggle, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, replace, arginfo_class_HTML5_DOM_DOMTokenList_replace, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, supports, arginfo_class_HTML5_DOM_DOMTokenList_supports, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, current, arginfo_class_HTML5_DOM_DOMTokenList_current, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, key, arginfo_class_HTML5_DOM_DOMTokenList_key, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, next, arginfo_class_HTML5_DOM_DOMTokenList_next, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, rewind, arginfo_class_HTML5_DOM_DOMTokenList_rewind, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, valid, arginfo_class_HTML5_DOM_DOMTokenList_valid, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, offsetExists, arginfo_class_HTML5_DOM_DOMTokenList_offsetExists, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, offsetGet, arginfo_class_HTML5_DOM_DOMTokenList_offsetGet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, offsetSet, arginfo_class_HTML5_DOM_DOMTokenList_offsetSet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, offsetUnset, arginfo_class_HTML5_DOM_DOMTokenList_offsetUnset, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_DOMTokenList, count, arginfo_class_HTML5_DOM_DOMTokenList_count, ZEND_ACC_PUBLIC)
	PHP_FE_END
};

/* HTML5\DOM\NamedNodeMap */
static zend_function_entry html5_dom_namednodemap_methods[] = {
	PHP_ME(HTML5_DOM_NamedNodeMap, item, arginfo_class_HTML5_DOM_NamedNodeMap_item, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, getNamedItem, arginfo_class_HTML5_DOM_NamedNodeMap_getNamedItem, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, getNamedItemNS, arginfo_class_HTML5_DOM_NamedNodeMap_getNamedItemNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, setNamedItem, arginfo_class_HTML5_DOM_NamedNodeMap_setNamedItem, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, setNamedItemNS, arginfo_class_HTML5_DOM_NamedNodeMap_setNamedItemNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, removeNamedItem, arginfo_class_HTML5_DOM_NamedNodeMap_removeNamedItem, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, removeNamedItemNS, arginfo_class_HTML5_DOM_NamedNodeMap_removeNamedItemNS, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, current, arginfo_class_HTML5_DOM_NamedNodeMap_current, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, key, arginfo_class_HTML5_DOM_NamedNodeMap_key, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, next, arginfo_class_HTML5_DOM_NamedNodeMap_next, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, rewind, arginfo_class_HTML5_DOM_NamedNodeMap_rewind, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, valid, arginfo_class_HTML5_DOM_NamedNodeMap_valid, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, offsetExists, arginfo_class_HTML5_DOM_NamedNodeMap_offsetExists, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, offsetGet, arginfo_class_HTML5_DOM_NamedNodeMap_offsetGet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, offsetSet, arginfo_class_HTML5_DOM_NamedNodeMap_offsetSet, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, offsetUnset, arginfo_class_HTML5_DOM_NamedNodeMap_offsetUnset, ZEND_ACC_PUBLIC)
	PHP_ME(HTML5_DOM_NamedNodeMap, count, arginfo_class_HTML5_DOM_NamedNodeMap_count, ZEND_ACC_PUBLIC)
	PHP_FE_END
};


/*
 * Functions
 * */
static zend_object *_create_object(zend_class_entry *ce TSRMLS_DC) {
	html5_dom_object_wrap_t *intern = html5_dom_object_wrap_create(ce, &object_handlers);
	
	/* HTML5\DOM\DOMException */
	if (ce == html5_dom_domexception_ce) {
		intern->prop_handler = &html5_dom_domexception_prop_handlers;
	}
	/* HTML5\DOM\Node */
	else if (ce == html5_dom_node_ce) {
		intern->prop_handler = &html5_dom_node_prop_handlers;
	}
	/* HTML5\DOM\Document */
	else if (ce == html5_dom_document_ce) {
		intern->prop_handler = &html5_dom_document_prop_handlers;
	}
	/* HTML5\DOM\DocumentFragment */
	else if (ce == html5_dom_documentfragment_ce) {
		intern->prop_handler = &html5_dom_documentfragment_prop_handlers;
	}
	/* HTML5\DOM\DocumentType */
	else if (ce == html5_dom_documenttype_ce) {
		intern->prop_handler = &html5_dom_documenttype_prop_handlers;
	}
	/* HTML5\DOM\Attr */
	else if (ce == html5_dom_attr_ce) {
		intern->prop_handler = &html5_dom_attr_prop_handlers;
	}
	/* HTML5\DOM\CharacterData */
	else if (ce == html5_dom_characterdata_ce) {
		intern->prop_handler = &html5_dom_characterdata_prop_handlers;
	}
	/* HTML5\DOM\Text */
	else if (ce == html5_dom_text_ce) {
		intern->prop_handler = &html5_dom_text_prop_handlers;
	}
	/* HTML5\DOM\CDATASection */
	else if (ce == html5_dom_cdatasection_ce) {
		intern->prop_handler = &html5_dom_cdatasection_prop_handlers;
	}
	/* HTML5\DOM\Comment */
	else if (ce == html5_dom_comment_ce) {
		intern->prop_handler = &html5_dom_comment_prop_handlers;
	}
	/* HTML5\DOM\ProcessingInstruction */
	else if (ce == html5_dom_processinginstruction_ce) {
		intern->prop_handler = &html5_dom_processinginstruction_prop_handlers;
	}
	/* HTML5\DOM\Element */
	else if (ce == html5_dom_element_ce) {
		intern->prop_handler = &html5_dom_element_prop_handlers;
	}
	/* HTML5\DOM\HTMLCollection */
	else if (ce == html5_dom_htmlcollection_ce) {
		intern->prop_handler = &html5_dom_htmlcollection_prop_handlers;
	}
	/* HTML5\DOM\NodeList */
	else if (ce == html5_dom_nodelist_ce) {
		intern->prop_handler = &html5_dom_nodelist_prop_handlers;
	}
	/* HTML5\DOM\DOMTokenList */
	else if (ce == html5_dom_domtokenlist_ce) {
		intern->prop_handler = &html5_dom_domtokenlist_prop_handlers;
	}
	/* HTML5\DOM\NamedNodeMap */
	else if (ce == html5_dom_namednodemap_ce) {
		intern->prop_handler = &html5_dom_namednodemap_prop_handlers;
	}
	/* Without properties */
	else {
		intern->prop_handler = NULL;
	}
	
	DOM_GC_TRACE("[NEW] %s (refs=%d)", ce->name->val, GC_REFCOUNT(&intern->std));
	
	return &intern->std;
}

static void _free_object(zend_object *object TSRMLS_DC) {
	html5_dom_object_wrap_t *intern = html5_dom_object_unwrap(object);
	
	DOM_GC_TRACE("[DESTROY] %s (refs=%d)", object->ce->name->val, GC_REFCOUNT(&intern->std));
	
	html5_dom_object_wrap_free(intern);
}

void html5_dom_interfaces_init() {
	memcpy(&object_handlers, zend_get_std_object_handlers(), sizeof(zend_object_handlers));
	object_handlers.offset					= XtOffsetOf(html5_dom_object_wrap_t, std);
	object_handlers.free_obj				= _free_object;
	object_handlers.clone_obj				= NULL;
	
	object_handlers.read_property			= html5_dom_read_property;
	object_handlers.write_property			= html5_dom_write_property;
	object_handlers.get_property_ptr_ptr	= html5_dom_get_property_ptr_ptr;
	object_handlers.has_property			= html5_dom_has_property;
	object_handlers.get_debug_info			= html5_dom_get_debug_info;
	
	zend_class_entry ce;

	/* HTML5\DOM */
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM", html5_dom_methods);
	ce.create_object = _create_object;
	html5_dom_ce = zend_register_internal_class(&ce);

	/* HTML5\DOM\Parser */
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Parser", html5_dom_parser_methods);
	ce.create_object = _create_object;
	html5_dom_parser_ce = zend_register_internal_class(&ce);

	/* HTML5\DOM\StreamParser */
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\StreamParser", html5_dom_streamparser_methods);
	ce.create_object = _create_object;
	html5_dom_streamparser_ce = zend_register_internal_class(&ce);

	/* HTML5\DOM\DOMException */
	html5_dom_prop_handlers_init_t html5_dom_domexception_handlers[] = {
		{"name", html5_dom_domexception__name, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_domexception_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_domexception_prop_handlers, html5_dom_domexception_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\DOMException", html5_dom_domexception_methods);
	ce.create_object = _create_object;
	html5_dom_domexception_ce = zend_register_internal_class_ex(&ce, zend_ce_exception);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INDEX_SIZE_ERR") - 1, LXB_DOM_INDEX_SIZE_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("DOMSTRING_SIZE_ERR") - 1, LXB_DOM_DOMSTRING_SIZE_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("HIERARCHY_REQUEST_ERR") - 1, LXB_DOM_HIERARCHY_REQUEST_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("WRONG_DOCUMENT_ERR") - 1, LXB_DOM_WRONG_DOCUMENT_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INVALID_CHARACTER_ERR") - 1, LXB_DOM_INVALID_CHARACTER_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("NO_DATA_ALLOWED_ERR") - 1, LXB_DOM_NO_DATA_ALLOWED_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("NO_MODIFICATION_ALLOWED_ERR") - 1, LXB_DOM_NO_MODIFICATION_ALLOWED_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("NOT_FOUND_ERR") - 1, LXB_DOM_NOT_FOUND_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("NOT_SUPPORTED_ERR") - 1, LXB_DOM_NOT_SUPPORTED_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INUSE_ATTRIBUTE_ERR") - 1, LXB_DOM_INUSE_ATTRIBUTE_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INVALID_STATE_ERR") - 1, LXB_DOM_INVALID_STATE_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("SYNTAX_ERR") - 1, LXB_DOM_SYNTAX_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INVALID_MODIFICATION_ERR") - 1, LXB_DOM_INVALID_MODIFICATION_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("NAMESPACE_ERR") - 1, LXB_DOM_NAMESPACE_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INVALID_ACCESS_ERR") - 1, LXB_DOM_INVALID_ACCESS_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("VALIDATION_ERR") - 1, LXB_DOM_VALIDATION_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("TYPE_MISMATCH_ERR") - 1, LXB_DOM_TYPE_MISMATCH_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("SECURITY_ERR") - 1, LXB_DOM_SECURITY_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("NETWORK_ERR") - 1, LXB_DOM_NETWORK_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("ABORT_ERR") - 1, LXB_DOM_ABORT_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("URL_MISMATCH_ERR") - 1, LXB_DOM_URL_MISMATCH_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("QUOTA_EXCEEDED_ERR") - 1, LXB_DOM_QUOTA_EXCEEDED_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("TIMEOUT_ERR") - 1, LXB_DOM_TIMEOUT_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("INVALID_NODE_TYPE_ERR") - 1, LXB_DOM_INVALID_NODE_TYPE_ERR);
	zend_declare_class_constant_long(html5_dom_domexception_ce, ZEND_STRS("DATA_CLONE_ERR") - 1, LXB_DOM_DATA_CLONE_ERR);

	/* HTML5\DOM\EventTarget */
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\EventTarget", html5_dom_eventtarget_methods);
	ce.create_object = _create_object;
	html5_dom_eventtarget_ce = zend_register_internal_class(&ce);

	/* HTML5\DOM\Node */
	html5_dom_prop_handlers_init_t html5_dom_node_handlers[] = {
		{"nodeType", html5_dom_node__nodeType, NULL}, 
		{"nodeName", html5_dom_node__nodeName, NULL}, 
		{"baseURI", html5_dom_node__baseURI, NULL}, 
		{"isConnected", html5_dom_node__isConnected, NULL}, 
		{"ownerDocument", html5_dom_node__ownerDocument, NULL}, 
		{"parentNode", html5_dom_node__parentNode, NULL}, 
		{"parentElement", html5_dom_node__parentElement, NULL}, 
		{"childNodes", html5_dom_node__childNodes, NULL}, 
		{"firstChild", html5_dom_node__firstChild, NULL}, 
		{"lastChild", html5_dom_node__lastChild, NULL}, 
		{"previousSibling", html5_dom_node__previousSibling, NULL}, 
		{"nextSibling", html5_dom_node__nextSibling, NULL}, 
		{"nodeValue", {html5_dom_node__nodeValue, html5_dom_node__nodeValue_set}}, 
		{"textContent", {html5_dom_node__textContent, html5_dom_node__textContent_set}}, 
		{"private", {html5_dom_node__private, html5_dom_node__private_set}}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_node_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_node_prop_handlers, html5_dom_node_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Node", html5_dom_node_methods);
	ce.create_object = _create_object;
	html5_dom_node_ce = zend_register_internal_class_ex(&ce, html5_dom_eventtarget_ce);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("ELEMENT_NODE") - 1, LXB_DOM_NODE_TYPE_ELEMENT);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("ATTRIBUTE_NODE") - 1, LXB_DOM_NODE_TYPE_ATTRIBUTE);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("TEXT_NODE") - 1, LXB_DOM_NODE_TYPE_TEXT);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("CDATA_SECTION_NODE") - 1, LXB_DOM_NODE_TYPE_CDATA_SECTION);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("ENTITY_REFERENCE_NODE") - 1, LXB_DOM_NODE_TYPE_ENTITY_REFERENCE);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("ENTITY_NODE") - 1, LXB_DOM_NODE_TYPE_ENTITY);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("PROCESSING_INSTRUCTION_NODE") - 1, LXB_DOM_NODE_TYPE_PROCESSING_INSTRUCTION);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("COMMENT_NODE") - 1, LXB_DOM_NODE_TYPE_COMMENT);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_NODE") - 1, LXB_DOM_NODE_TYPE_DOCUMENT);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_TYPE_NODE") - 1, LXB_DOM_NODE_TYPE_DOCUMENT_TYPE);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_FRAGMENT_NODE") - 1, LXB_DOM_NODE_TYPE_DOCUMENT_FRAGMENT);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("NOTATION_NODE") - 1, LXB_DOM_NODE_TYPE_NOTATION);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_POSITION_DISCONNECTED") - 1, HTML5_DOM_Node__DOCUMENT_POSITION_DISCONNECTED);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_POSITION_PRECEDING") - 1, HTML5_DOM_Node__DOCUMENT_POSITION_PRECEDING);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_POSITION_FOLLOWING") - 1, HTML5_DOM_Node__DOCUMENT_POSITION_FOLLOWING);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_POSITION_CONTAINS") - 1, HTML5_DOM_Node__DOCUMENT_POSITION_CONTAINS);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_POSITION_CONTAINED_BY") - 1, HTML5_DOM_Node__DOCUMENT_POSITION_CONTAINED_BY);
	zend_declare_class_constant_long(html5_dom_node_ce, ZEND_STRS("DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC") - 1, HTML5_DOM_Node__DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC);

	/* HTML5\DOM\Document */
	html5_dom_prop_handlers_init_t html5_dom_document_handlers[] = {
		{"URL", html5_dom_document__URL, NULL}, 
		{"documentURI", html5_dom_document__documentURI, NULL}, 
		{"origin", html5_dom_document__origin, NULL}, 
		{"compatMode", html5_dom_document__compatMode, NULL}, 
		{"characterSet", html5_dom_document__characterSet, NULL}, 
		{"charset", html5_dom_document__charset, NULL}, 
		{"inputEncoding", html5_dom_document__inputEncoding, NULL}, 
		{"contentType", html5_dom_document__contentType, NULL}, 
		{"doctype", html5_dom_document__doctype, NULL}, 
		{"documentElement", html5_dom_document__documentElement, NULL}, 
		{"children", html5_dom_parentnode__children, NULL}, 
		{"firstElementChild", html5_dom_parentnode__firstElementChild, NULL}, 
		{"lastElementChild", html5_dom_parentnode__lastElementChild, NULL}, 
		{"childElementCount", html5_dom_parentnode__childElementCount, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_document_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_document_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_document_prop_handlers, html5_dom_document_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Document", html5_dom_document_methods);
	ce.create_object = _create_object;
	html5_dom_document_ce = zend_register_internal_class_ex(&ce, html5_dom_node_ce);

	/* HTML5\DOM\DocumentFragment */
	html5_dom_prop_handlers_init_t html5_dom_documentfragment_handlers[] = {
		{"children", html5_dom_parentnode__children, NULL}, 
		{"firstElementChild", html5_dom_parentnode__firstElementChild, NULL}, 
		{"lastElementChild", html5_dom_parentnode__lastElementChild, NULL}, 
		{"childElementCount", html5_dom_parentnode__childElementCount, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_documentfragment_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_documentfragment_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_documentfragment_prop_handlers, html5_dom_documentfragment_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\DocumentFragment", html5_dom_documentfragment_methods);
	ce.create_object = _create_object;
	html5_dom_documentfragment_ce = zend_register_internal_class_ex(&ce, html5_dom_node_ce);

	/* HTML5\DOM\DocumentType */
	html5_dom_prop_handlers_init_t html5_dom_documenttype_handlers[] = {
		{"name", html5_dom_documenttype__name, NULL}, 
		{"publicId", html5_dom_documenttype__publicId, NULL}, 
		{"systemId", html5_dom_documenttype__systemId, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_documenttype_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_documenttype_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_documenttype_prop_handlers, html5_dom_documenttype_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\DocumentType", html5_dom_documenttype_methods);
	ce.create_object = _create_object;
	html5_dom_documenttype_ce = zend_register_internal_class_ex(&ce, html5_dom_node_ce);

	/* HTML5\DOM\Attr */
	html5_dom_prop_handlers_init_t html5_dom_attr_handlers[] = {
		{"namespaceURI", html5_dom_attr__namespaceURI, NULL}, 
		{"prefix", html5_dom_attr__prefix, NULL}, 
		{"localName", html5_dom_attr__localName, NULL}, 
		{"name", html5_dom_attr__name, NULL}, 
		{"value", {html5_dom_attr__value, html5_dom_attr__value_set}}, 
		{"ownerElement", html5_dom_attr__ownerElement, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_attr_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_attr_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_attr_prop_handlers, html5_dom_attr_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Attr", html5_dom_attr_methods);
	ce.create_object = _create_object;
	html5_dom_attr_ce = zend_register_internal_class_ex(&ce, html5_dom_node_ce);

	/* HTML5\DOM\CharacterData */
	html5_dom_prop_handlers_init_t html5_dom_characterdata_handlers[] = {
		{"data", {html5_dom_characterdata__data, html5_dom_characterdata__data_set}}, 
		{"length", html5_dom_characterdata__length, NULL}, 
		{"previousElementSibling", html5_dom_nondocumenttypechildnode__previousElementSibling, NULL}, 
		{"nextElementSibling", html5_dom_nondocumenttypechildnode__nextElementSibling, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_characterdata_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_characterdata_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_characterdata_prop_handlers, html5_dom_characterdata_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\CharacterData", html5_dom_characterdata_methods);
	ce.create_object = _create_object;
	html5_dom_characterdata_ce = zend_register_internal_class_ex(&ce, html5_dom_node_ce);

	/* HTML5\DOM\Text */
	html5_dom_prop_handlers_init_t html5_dom_text_handlers[] = {
		{"wholeText", html5_dom_text__wholeText, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_text_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_text_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_text_prop_handlers, html5_dom_characterdata_handlers);
	html5_dom_prop_handler_add(&html5_dom_text_prop_handlers, html5_dom_text_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Text", html5_dom_text_methods);
	ce.create_object = _create_object;
	html5_dom_text_ce = zend_register_internal_class_ex(&ce, html5_dom_characterdata_ce);

	/* HTML5\DOM\CDATASection */
	html5_dom_prop_handler_init(&html5_dom_cdatasection_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_cdatasection_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_cdatasection_prop_handlers, html5_dom_characterdata_handlers);
	html5_dom_prop_handler_add(&html5_dom_cdatasection_prop_handlers, html5_dom_text_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\CDATASection", html5_dom_cdatasection_methods);
	ce.create_object = _create_object;
	html5_dom_cdatasection_ce = zend_register_internal_class_ex(&ce, html5_dom_text_ce);

	/* HTML5\DOM\Comment */
	html5_dom_prop_handler_init(&html5_dom_comment_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_comment_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_comment_prop_handlers, html5_dom_characterdata_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Comment", html5_dom_comment_methods);
	ce.create_object = _create_object;
	html5_dom_comment_ce = zend_register_internal_class_ex(&ce, html5_dom_characterdata_ce);

	/* HTML5\DOM\ProcessingInstruction */
	html5_dom_prop_handlers_init_t html5_dom_processinginstruction_handlers[] = {
		{"target", html5_dom_processinginstruction__target, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_processinginstruction_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_processinginstruction_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_processinginstruction_prop_handlers, html5_dom_characterdata_handlers);
	html5_dom_prop_handler_add(&html5_dom_processinginstruction_prop_handlers, html5_dom_processinginstruction_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\ProcessingInstruction", html5_dom_processinginstruction_methods);
	ce.create_object = _create_object;
	html5_dom_processinginstruction_ce = zend_register_internal_class_ex(&ce, html5_dom_characterdata_ce);

	/* HTML5\DOM\Element */
	html5_dom_prop_handlers_init_t html5_dom_element_handlers[] = {
		{"namespaceURI", html5_dom_element__namespaceURI, NULL}, 
		{"prefix", html5_dom_element__prefix, NULL}, 
		{"localName", html5_dom_element__localName, NULL}, 
		{"tagName", html5_dom_element__tagName, NULL}, 
		{"id", {html5_dom_element__id, html5_dom_element__id_set}}, 
		{"className", {html5_dom_element__className, html5_dom_element__className_set}}, 
		{"classList", html5_dom_element__classList, NULL}, 
		{"attributes", html5_dom_element__attributes, NULL}, 
		{"innerHTML", {html5_dom_element__innerHTML, html5_dom_element__innerHTML_set}}, 
		{"outerHTML", {html5_dom_element__outerHTML, html5_dom_element__outerHTML_set}}, 
		{"children", html5_dom_parentnode__children, NULL}, 
		{"firstElementChild", html5_dom_parentnode__firstElementChild, NULL}, 
		{"lastElementChild", html5_dom_parentnode__lastElementChild, NULL}, 
		{"childElementCount", html5_dom_parentnode__childElementCount, NULL}, 
		{"previousElementSibling", html5_dom_nondocumenttypechildnode__previousElementSibling, NULL}, 
		{"nextElementSibling", html5_dom_nondocumenttypechildnode__nextElementSibling, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_element_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_element_prop_handlers, html5_dom_node_handlers);
	html5_dom_prop_handler_add(&html5_dom_element_prop_handlers, html5_dom_element_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\Element", html5_dom_element_methods);
	ce.create_object = _create_object;
	html5_dom_element_ce = zend_register_internal_class_ex(&ce, html5_dom_node_ce);

	/* HTML5\DOM\HTMLCollection */
	html5_dom_prop_handlers_init_t html5_dom_htmlcollection_handlers[] = {
		{"length", html5_dom_htmlcollection__length, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_htmlcollection_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_htmlcollection_prop_handlers, html5_dom_htmlcollection_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\HTMLCollection", html5_dom_htmlcollection_methods);
	ce.create_object = _create_object;
	html5_dom_htmlcollection_ce = zend_register_internal_class(&ce);
	zend_class_implements(html5_dom_htmlcollection_ce, 3, zend_ce_iterator, zend_ce_arrayaccess, zend_ce_countable);

	/* HTML5\DOM\NodeList */
	html5_dom_prop_handlers_init_t html5_dom_nodelist_handlers[] = {
		{"length", html5_dom_nodelist__length, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_nodelist_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_nodelist_prop_handlers, html5_dom_nodelist_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\NodeList", html5_dom_nodelist_methods);
	ce.create_object = _create_object;
	html5_dom_nodelist_ce = zend_register_internal_class(&ce);
	zend_class_implements(html5_dom_nodelist_ce, 3, zend_ce_iterator, zend_ce_arrayaccess, zend_ce_countable);

	/* HTML5\DOM\DOMTokenList */
	html5_dom_prop_handlers_init_t html5_dom_domtokenlist_handlers[] = {
		{"length", html5_dom_domtokenlist__length, NULL}, 
		{"value", {html5_dom_domtokenlist__value, html5_dom_domtokenlist__value_set}}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_domtokenlist_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_domtokenlist_prop_handlers, html5_dom_domtokenlist_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\DOMTokenList", html5_dom_domtokenlist_methods);
	ce.create_object = _create_object;
	html5_dom_domtokenlist_ce = zend_register_internal_class(&ce);
	zend_class_implements(html5_dom_domtokenlist_ce, 3, zend_ce_iterator, zend_ce_arrayaccess, zend_ce_countable);

	/* HTML5\DOM\NamedNodeMap */
	html5_dom_prop_handlers_init_t html5_dom_namednodemap_handlers[] = {
		{"length", html5_dom_namednodemap__length, NULL}, 
		{"", NULL}, 
	};
	html5_dom_prop_handler_init(&html5_dom_namednodemap_prop_handlers);
	html5_dom_prop_handler_add(&html5_dom_namednodemap_prop_handlers, html5_dom_namednodemap_handlers);
	INIT_CLASS_ENTRY(ce, "HTML5\\DOM\\NamedNodeMap", html5_dom_namednodemap_methods);
	ce.create_object = _create_object;
	html5_dom_namednodemap_ce = zend_register_internal_class(&ce);
	zend_class_implements(html5_dom_namednodemap_ce, 3, zend_ce_iterator, zend_ce_arrayaccess, zend_ce_countable);

}

void html5_dom_interfaces_unload() {
	html5_dom_prop_handler_free(&html5_dom_domexception_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_node_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_document_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_documentfragment_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_documenttype_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_attr_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_characterdata_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_text_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_cdatasection_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_comment_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_processinginstruction_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_element_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_htmlcollection_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_nodelist_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_domtokenlist_prop_handlers);
	html5_dom_prop_handler_free(&html5_dom_namednodemap_prop_handlers);
}
